spring:
  application:
    name: Metapor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/METAPOR?createDatabaseIfNotExist=true
    username: METAPOR
    password: METAPOR
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 100
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true



jwt:
  secret: hgy78uijhgyt67y8uhtf5r6t7yuhgfrd56t7yuhgcrd56t7y8ihjgcrd567ty8ihgcrs45er6t7y8u9i0thj4329u8ehw32rbji49euh
  access:
    expiration: 2592000000 #60*60*24*30000
  refresh:
    expiration: 2592000000 #60*60*24*30000


security-config:
  cors:
    allowed-origins: http://localhost:3000

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true